# Generated by Django 3.2.19 on 2023-06-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20230610_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PROFESSOR', 'Not a student'), ('STUDENT', 'Student')], default='STUDENT', max_length=10, verbose_name='User Status'),
        ),
    ]
