# Generated by Django 3.2.19 on 2023-07-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20230716_0247'),
        ('coreapp', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.universitydepartment'),
        ),
        migrations.DeleteModel(
            name='UniversityDepartment',
        ),
    ]
